auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: YES!CODING! --ccyjava's blog
url: http://www.yescoding.com
feed: /atom.xml
author_info: <a href="http://www.yescoding.com/">CCYJAVA</a>
